# Generated by Django 5.2.1 on 2025-06-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
