"""
Django settings for the config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-se*+7f6m+_anqy-ftqv$xuk^@+#1@n(-i+hziugch+=0oieb43'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'api',

    'users',
    'recipes',
    'shopping',
    'measurements',
    'media',
    'rest_framework_simplejwt.token_blacklist'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

SIMPLE_JWT = {
    # ... tus otras configuraciones de SIMPLE_JWT

    'BLACKLIST_ENABLED': True, # <--- ¡Añade o asegura que esta línea esté en True!
    'BLACKLIST_AFTER_ROTATION': False, # Si no vas a rotar tokens al refrescar, puedes dejarlo en False.
                                     # Si habilitas rotación, True es la práctica común.
                                     # Para un logout simple, False funciona bien.

    # ... otras configuraciones como el tiempo de vida de los tokens
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5), # O el tiempo que tengas configurado
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # O el tiempo que tengas configurado
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'cookflow_db',
        'USER': 'admin',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#         'django_filters.rest_framework.DjangoFilterBackend'
#     )
# }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_IMAGE_MODEL = 'media.Image'
AUTH_RECIPE_MODEL = 'recipes.Recipe'
AUTH_CATEGORY_MODEL = 'recipes.Category'
AUTH_INGREDIENT_MODEL = 'recipes.Ingredient'
AUTH_RECIPEINGREDIENT_MODEL = 'recipes.RecipeIngredient'
AUTH_STEP_MODEL = 'recipes.Step'
AUTH_SHOPPINGLISTITEM_MODEL = 'shopping.ShoppingListItem'
AUTH_USER_MODEL = 'users.CustomUser'
AUTH_FAVORITE_MODEL = 'recipes.Favorite'
AUTH_UNIT_MODEL = 'measurements.Unit'
AUTH_UNITTYPE_MODEL = 'measurements.UnitType'

# Configuration for Django's password hashing algorithms.
# The first hasher in this list will be used to hash all new passwords.
# Subsequent hashers are kept to allow verification of passwords
# hashed with older algorithms, facilitating a gradual migration of
# existing passwords to Argon2.

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Optional configuration for Argon2.
# You can adjust these values to modify the hashing resistance.
# Keep in mind that higher values will increase security, but also the time
# and resources required to hash passwords.
# Django's default values are typically conservative but secure.
# For a balance between robust security and performance on varied hardware.

# Values explanation:
# 'time_cost': Number of iterations. Increased for better brute-force attack resistance.
# This value may vary depending on CPU power.
# 'memory_cost': Memory size in KiB (1 MiB). Increased for greater resistance
# to specialized hardware attacks (ASIC/GPU). Consider 4096 (4 MiB).
# 'parallelism: Number of CPUs/cores to use in parallel.
# it is common to avoid server overload while maintaining effectiveness.

ARGON2_DEFAULTS = {
    'time_cost': 4,
    'memory_cost': 4096,
    'parallelism': 2
}

# --- Absolute Minimum Reference (NOT RECOMMENDED FOR PRODUCTION) ---
# This section provides a theoretical "absolute minimum" configuration for Argon2
# parameters for purely illustrative purposes, showing the lowest practical values.
# Using these minimums in a production environment would significantly compromise
# password security due to their low computational cost, making brute-force
# attacks relatively easy and fast. These values are NOT secure.
#
# 'time_cost': 1          # Bare minimum iterations. Extremely weak against brute-force.
# 'memory_cost': 8        # Bare minimum memory (8 KiB). Highly vulnerable to GPU/ASIC attacks.
# 'parallelism': 1        # Bare minimum parallelism.
# -------------------------------------------------------------------
MEDIA_IMG_PATH = BASE_DIR / 'media' / 'img'