# Generated by Django 5.2.3 on 2025-06-14 14:52

import django.db.models.deletion
import recipes.models.category
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_alter_unit_unit_type'),
        ('recipes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category_id',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='categories',
            field=models.ManyToManyField(db_table='categories_ingredients', related_name='ingredients', to='recipes.category'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(db_table='categories_recipes', related_name='recipes', to='recipes.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user_id',
            field=models.ForeignKey(default=recipes.models.category.default_user, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurements.unit'),
        ),
    ]
