# Generated by Django 5.2.1 on 2025-06-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category_id',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='categories',
            field=models.ManyToManyField(db_table='categories_ingredients', related_name='ingredients', to='recipes.category'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(db_table='categories_recipes', related_name='recipes', to='recipes.category'),
        ),
    ]
