# Generated by Django 5.2.1 on 2025-06-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
