# Generated by Django 5.2.3 on 2025-06-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_recipe_id_step_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
