# Generated by Django 5.2.3 on 2025-06-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipeingredient_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='updated_at',
        ),
    ]
