# Generated by Django 5.2.1 on 2025-06-10 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_unit_user_id'),
        ('shopping', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurements.unit'),
        ),
    ]
