# Generated by Django 5.2.3 on 2025-06-14 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_alter_unit_unit_type'),
        ('shopping', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurements.unit'),
        ),
    ]
