# Generated by Django 5.2.3 on 2025-06-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_shoppinglistitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
