# cookflow-backend/.github/workflows/ci.yml
name: Backend CI & E2E Trigger

on:
  push:
    branches: [main, dev]
  pull_request: # Also runs on PRs, but only triggers E2E on pushes to main/dev
    branches: [main, dev]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # From Org Secret
          password: ${{ secrets.DOCKER_PASSWORD }} # From Org Secret

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # Builds from the root of this backend repo
          push: true
          # Tag the image with 'latest' and the commit SHA
          # IMPORTANT: Replace 'your_docker_registry_username' with your actual username/org
          tags: |
            hemaps/cookflow-backend:latest # <--- Updated to hemaps
            hemaps/cookflow-backend:${{ github.sha }} # <--- Updated to hemaps

      - name: Trigger Frontend E2E Tests (Cross-Repo)
        # Only trigger E2E for actual pushes to main/dev, not PRs
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.REPO_DISPATCH_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository_owner }}/cookflow-frontend/dispatches \
          -d '{"event_type": "backend_update", "client_payload": {"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}}'